const product = [
  {
    id: 1,
    name: 'buttermilk pancakes',
    category: 'electronics',
    price: 68.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-mousepad-2.jpg',
  },
  {
    id: 2,
    name: 'Notebook Stand',
    category: 'electronics',
    price: 109.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-stand-1.jpg',
  },
  {
    id: 3,
    name: 'Apple MacBook Air',
    category: 'fashion',
    price: 8999.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-apple-2.jpg',
  },
  {
    id: 4,
    name: 'DJI Osmo Mobile 3 Combo',
    category: 'fashion',
    price: 665.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/03/shop43-mobile-combo-2.jpg',
  },
  {
    id: 5,
    name: 'HP Ink Tank',
    category: 'fashion',
    price: 22.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-ink-4.jpg',
  },
  {
    id: 6,
    name: 'Intelbras Action RF1200',
    category: 'fashion',
    price: 18.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-Intelbras-3.jpg',
  },
  {
    id: 7,
    name: 'JBL TUNE 510BT',
    category: 'fashion',
    price: 999.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-jbl-tune-1.jpg',
  },
  {
    id: 8,
    name: 'Samsung galaxy A54',
    category: 'fashion',
    price: 69.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/sho43-galaxy-3.jpg',
  },
  {
    id: 9,
    name: 'Toshiba Canvio Basics 3.0',
    category: 'fashion',
    price: 8996.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-toshibav-canvio-2.jpg',
  },
  {
    id: 10,
    name: 'LG WK600-W',
    category: 'gifts',
    price: 1559.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-lg-monitor-3.jpg',
  },
  {
    id: 11,
    name: 'Logitech MK540 Wireless Keyboard/Mouse',
    category: 'fashion',
    price: 1933.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-keyboard-mouse-1.jpg',
  },
  {
    id: 12,
    name: 'Toshiba Canvio Basics 3.0',
    category: 'fashion',
    price: 16.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-toshibav-canvio-2.jpg',
  },
  {
    id: 13,
    name: 'Toshiba Canvio Basics 3.0',
    category: 'fashion',
    price: 1999.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-toshiba-canvio-3.jpg',
  },
  {
    id: 14,
    name: 'Apple MacBook Air',
    category: 'Home & Garden',
    price: 8999.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-apple-2.jpg',
  },
  {
    id: 15,
    name: 'DJI Osmo Mobile 3 Combo',
    category: 'Home & Garden',
    price: 665.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/03/shop43-mobile-combo-2.jpg',
  },
  {
    id: 16,
    name: 'HP Ink Tank',
    category: 'Home & Garden',
    price: 22.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-ink-4.jpg',
  },
  {
    id: 17,
    name: 'buttermilk pancakes',
    category: 'Music',
    price: 68.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-mousepad-2.jpg',
  },
  {
    id: 18,
    name: 'Notebook Stand',
    category: 'Music',
    price: 109.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-stand-1.jpg',
  },
  {
    id: 19,
    name: 'Apple MacBook Air',
    category: 'Music',
    price: 8999.00,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/06/shop43-apple-2.jpg',
  },
  {
    id: 20,
    name: 'DJI Osmo Mobile 3 Combo',
    category: 'sports',
    price: 665.99,
    img: 'https://www.portotheme.com/wordpress/porto/shop43/wp-content/uploads/sites/222/2023/03/shop43-mobile-combo-2.jpg',
  },
];

export default product;
